# 

In [2]:
%%capture

!pip install numpy

In [3]:
import numpy as np



In [10]:
list1 = [1,2,3,4]


arr1 =  np.array(list1, dtype=np.float64)
print(arr1)

[1. 2. 3. 4.]


In [11]:
arr1.dtype

dtype('float64')

In [12]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [23]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Element-wise multiplication

print("Element-wise Multiplication:\n", A * B)

# Matrix multiplication (dot product)
# np.dot(A,B)
A@B# alternative to np.dot(A,B)





Element-wise Multiplication:
 [[ 5 12]
 [21 32]]


array([[19, 22],
       [43, 50]])

In [24]:
print(A)
print(A.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [25]:
from numpy.linalg import inv

A = np.array([[1, 2], [3, 4]])
print("Inverse:\n", inv(A))

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


$y =  2\pi \omega x $


In [26]:
A.shape

(2, 2)

In [28]:
A.size

4

In [29]:
A.ndim

2